### ISSUE TITLE
[Tracking] Beta 1 Roadmap

### ISSUE THREAD

**Issue by Akhliskun** [Akhliskun/firefox-infra-changelog#20]
This issue will track all the progress/bugs/requests and ToDos.
Fell free to use this Issue to discuses about steps, plans and ideas on what should go into the first release of FF-Infra
## Deadline:
5th November 2018

## What needs to be done:  [JIRA-like Board View](https://github.com/Akhliskun/firefox-infra-changelog/projects/1)
- [x] Initial issues, linked to milestone and with tags.
- [x] Github Login/Auth integration + examples + documentation.
- [x] HG wrapper/auth integration
- [x] JSON changelog, iteration 1 completed.
- [x] MarkDown changelog, iteration 1 completed.
- [x] Start to End, working prototype. (We get 2 changelogs, 1 .json 1 .md)
- [x] 5th Meeting with Jordan + Notes completed.

**Comment by bccrisan** [comment]
So,
At the moment we have completed the following:
- Github Login/Auth integration + examples + documentation.
-  HG wrapper/auth integration (we have handler function that takes the data from hg.m.o and does not require auth integration).
- We have the JSON changelog work in progress, (riman takes care of that)
- MarkDown is currently generated for the main table (I am currently working on that part, mostly finished it) and also generated for every github repository. The part that currently (I believe but I also may be wrong) is the HG markdown that may not be generated.
- All of the code it is able to run and handle/generate all of data/tables required.
- The notes for the meeting from 5th November can be found in the "CIDuty Staff Meeting"

**Comment by zsoltfay** [comment]
We've also linked every active issue to a milestone. This first major step has been completed.
